import React,{useEffect,useRef,useState} from 'react';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import {SafeAreaView,ScrollView,View,Text,TextInput,Pressable,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import {Session,createClient,money,ApiError} from '@vayyom/shared';
type Row=Record<string,any>;
const base=process.env.EXPO_PUBLIC_API_URL||'http://10.0.2.2:4000/api/v1';
export default function App(){
 const [session,setSession]=useState<Session|null>(null),[store,setStore]=useState(''),[stores,setStores]=useState<Row[]>([]),[tab,setTab]=useState('Today'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[rows,setRows]=useState<Row[]>([]),[dashboard,setDashboard]=useState<Row|null>(null),[invoice,setInvoice]=useState<Row|null>(null),[amount,setAmount]=useState(''),[method,setMethod]=useState('CASH'),[reference,setReference]=useState(''),[customers,setCustomers]=useState<Row[]>([]),[services,setServices]=useState<Row[]>([]),[employees,setEmployees]=useState<Row[]>([]),[booking,setBooking]=useState(false),[customerId,setCustomerId]=useState(''),[serviceId,setServiceId]=useState(''),[providerId,setProviderId]=useState(''),[startsAt,setStartsAt]=useState(''),[items,setItems]=useState<string[]>([]),[stockProduct,setStockProduct]=useState<Row|null>(null),[quantity,setQuantity]=useState(''),[reason,setReason]=useState('');
 const ref=useRef({session,store});ref.current={session,store};
 const api=useRef(createClient(base,()=>ref.current.session,()=>ref.current.store)).current;
 const canBill=!!session&&['ADMIN','MANAGER','RECEPTION'].includes(session.user.role),manager=!!session&&['ADMIN','MANAGER'].includes(session.user.role),inventory=!!session&&['ADMIN','MANAGER','INVENTORY'].includes(session.user.role);
 const tabs=session?.user.role==='INVENTORY'?['Stock','More']:session?.user.role==='THERAPIST'?['Appointments','More']:['Today','Appointments','Billing','Stock','More'];
 async function clear(){await SecureStore.deleteItemAsync('vayyom-session');setSession(null);setStores([]);setRows([]);setDashboard(null);setPassword('');}
 useEffect(()=>{SecureStore.getItemAsync('vayyom-session').then(value=>{if(value){try{const s=JSON.parse(value);setSession(s);setStore(s.user.storeIds[0]);setTab(s.user.role==='THERAPIST'?'Appointments':s.user.role==='INVENTORY'?'Stock':'Today');}catch{SecureStore.deleteItemAsync('vayyom-session');}}});},[]);
 async function execute(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===401&&session)await clear();}finally{setBusy(false);}}
 async function load(){
  if(!session)return;
  const loadedStores=await api<Row[]>('/stores');setStores(loadedStores);
  if(tab==='Today'){setDashboard(await api('/reports/dashboard'));return;}
  if(tab==='Appointments'){
   const [appts,srv,staff]=await Promise.all([api<Row[]>('/appointments'),api<Row[]>('/services'),api<Row[]>('/employees')]);setRows(appts);setServices(srv);setEmployees(staff);
   if(canBill)setCustomers(await api('/customers'));return;
  }
  if(tab==='Billing'){const [inv,cust,srv,products]=await Promise.all([api<Row[]>('/invoices'),api<Row[]>('/customers'),api<Row[]>('/services'),api<Row[]>('/products')]);setRows(inv);setCustomers(cust);setServices([...srv,...products]);return;}
  if(tab==='Stock'){setRows(await api('/stock'));return;}
  setRows(manager?await api('/notifications'):[]);
 }
 useEffect(()=>{setRows([]);setDashboard(null);setInvoice(null);setStockProduct(null);setBooking(false);setItems([]);setCustomerId('');if(session){setBusy(true);setError('');load().catch(async e=>{setError(e.message);if(e instanceof ApiError&&e.status===401)await clear();}).finally(()=>setBusy(false));}},[session,store,tab]);
 async function login(){await execute(async()=>{const s=await api<Session>('/auth/login',{username,password});await SecureStore.setItemAsync('vayyom-session',JSON.stringify(s));setSession(s);setStore(s.user.storeIds[0]);setPassword('');setTab(s.user.role==='THERAPIST'?'Appointments':s.user.role==='INVENTORY'?'Stock':'Today');});}
 const action=(path:string,body:unknown,after?:()=>void)=>execute(async()=>{await api(path,body);after?.();await load();});
 const button=(label:string,fn:()=>void,secondary=false)=><Pressable accessibilityRole="button" disabled={busy} onPress={fn} style={[s.button,secondary&&s.secondary,busy&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{label}</Text></Pressable>;
 const field=(label:string,value:string,change:(v:string)=>void,numeric=false)=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={change} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none"/></View>;
 const choices=(label:string,data:Row[],value:string,change:(v:string)=>void)=><View style={s.field}><Text style={s.label}>{label}</Text><ScrollView horizontal>{data.map(i=><Pressable key={i.id} onPress={()=>change(i.id)} style={[s.chip,value===i.id&&s.chipSelected]}><Text style={value===i.id?s.chipSelectedText:s.chipText}>{i.name}</Text></Pressable>)}</ScrollView></View>;
 return <SafeAreaView style={s.root}><StatusBar style="dark"/>{!session?<ScrollView contentContainerStyle={s.login}><Text style={s.logo}>✦ VAYYOM</Text><Text style={s.eyebrow}>SPA & WELLNESS</Text><Text style={s.title}>Welcome to your studio.</Text><Text style={s.subtitle}>A little more calm. A lot more clarity.</Text>{field('Username',username,setUsername)}<View style={s.field}><Text style={s.label}>Password</Text><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none"/></View>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{button(busy?'Signing in…':'Sign in',login)}<Text style={s.hint}>Staff workspace · Phase 1</Text></ScrollView>:<><View style={s.header}><View><Text style={s.logo}>✦ VAYYOM</Text><Text style={s.eyebrow}>YOUR STUDIO, CONNECTED</Text></View><Text style={s.role}>{session.user.role}</Text></View><ScrollView contentContainerStyle={s.content}><ScrollView horizontal style={{marginBottom:20}}>{stores.map(st=><Pressable key={st.id} onPress={()=>!busy&&setStore(st.id)} style={[s.chip,store===st.id&&s.chipSelected]}><Text style={store===st.id?s.chipSelectedText:s.chipText}>{st.name}</Text></Pressable>)}</ScrollView><Text style={s.title}>{tab==='Today'?'Hello, '+session.user.name.split(' ')[0]+'.':tab}</Text><Text style={s.subtitle}>Thoughtful care. Seamless operations.</Text>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{busy&&<ActivityIndicator color="#174f43"/>}{button('Refresh',()=>execute(load),true)}
 {tab==='Today'&&dashboard&&<><View style={s.grid}>{[['Collected',money(dashboard.collected)],['Outstanding',money(dashboard.outstanding)],['Guests',dashboard.customers],['Pending UPI',dashboard.pending]].map(([label,value])=><View key={String(label)} style={s.metric}><Text style={s.label}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>)}</View><Text style={s.section}>Upcoming visits</Text>{dashboard.appointments.map((a:Row)=><View key={a.id} style={s.card}><Text style={s.cardTitle}>{new Date(a.startsAt).toLocaleString()}</Text><Text style={s.subtitle}>{a.status.replaceAll('_',' ')}</Text></View>)}{!dashboard.appointments.length&&<Text style={s.empty}>Your next appointment will appear here.</Text>}<Text style={s.hint}>All-time totals · {new Date(dashboard.lastUpdated).toLocaleTimeString()}</Text></>}
 {tab==='Appointments'&&<>{canBill&&button(booking?'Close booking':'New appointment',()=>setBooking(!booking))}{booking&&<View style={s.card}>{choices('Guest',customers,customerId,setCustomerId)}{choices('Service',services,serviceId,setServiceId)}{choices('Therapist',employees.filter(e=>['ADMIN','MANAGER','THERAPIST'].includes(e.role)),providerId,setProviderId)}{field('Start: YYYY-MM-DDTHH:mm (device timezone)',startsAt,setStartsAt)}{button('Book appointment',()=>{if(!customerId||!serviceId||!providerId||Number.isNaN(Date.parse(startsAt))){setError('Choose a guest, service, therapist, and valid start time');return;}action('/appointments',{customerId,serviceId,providerId,startsAt:new Date(startsAt).toISOString()},()=>setBooking(false));})}</View>}{rows.map(a=><View key={a.id} style={s.card}><Text style={s.cardTitle}>{a.customerName}</Text><Text style={s.subtitle}>{a.serviceName} · {new Date(a.startsAt).toLocaleString()}</Text><Text style={s.status}>{a.status.replaceAll('_',' ')}</Text>{(a.status==='CONFIRMED'?['CHECKED_IN','CANCELLED','NO_SHOW']:a.status==='CHECKED_IN'?['IN_PROGRESS','CANCELLED']:a.status==='IN_PROGRESS'?['COMPLETED']:[]).map(status=><View key={status}>{button(status.replaceAll('_',' '),()=>action('/appointments/'+a.id+'/transition',{status,version:a.version}),true)}</View>)}</View>)}</>}
 {tab==='Billing'&&<>{button(booking?'Close new bill':'New invoice',()=>{setBooking(!booking);setInvoice(null);})}{booking&&<View style={s.card}>{choices('Guest',customers,customerId,setCustomerId)}<Text style={s.label}>Tap items to add one unit</Text>{services.map(item=><View key={item.id}>{button(item.name+' · '+money(item.price)+(items.includes(item.id)?' ✓':''),()=>setItems(old=>old.includes(item.id)?old.filter(id=>id!==item.id):[...old,item.id]),true)}</View>)}{button('Post invoice',()=>{if(!customerId||!items.length){setError('Select a guest and at least one item');return;}action('/invoices',{customerId,items:items.map(catalogItemId=>({catalogItemId,quantity:1})),discountPercent:'0'},()=>{setBooking(false);setItems([]);});})}</View>}{invoice&&<View style={s.card}><Text style={s.cardTitle}>Collect · {invoice.number}</Text>{choices('Method',[{id:'CASH',name:'Cash'},{id:'UPI',name:'UPI'}],method,setMethod)}{field('Amount (INR)',amount,setAmount,true)}{method==='UPI'&&field('UPI transaction reference',reference,setReference)}{button('Record payment',()=>action('/payments',{invoiceId:invoice.id,method,amount,...(method==='UPI'?{reference}:{})},()=>{setInvoice(null);setReference('');setAmount('');}))}{button('Cancel',()=>setInvoice(null),true)}</View>}{rows.map(i=><View key={i.id} style={s.card}><Text style={s.cardTitle}>{i.number}</Text><Text style={s.subtitle}>{customers.find(c=>c.id===i.customerId)?.name}</Text><Text style={s.metricValue}>{money(i.grandTotal)}</Text><Text style={s.subtitle}>Paid {money(i.paidTotal)} · Due {money(i.dueTotal)}</Text>{Number(i.dueTotal)>0&&button('Collect payment',()=>{setInvoice(i);setAmount(i.dueTotal);setBooking(false);})}{i.payments.map((p:Row)=><View key={p.id}><Text style={s.hint}>{p.method} · {money(p.amount)} · {p.status}</Text>{p.receiptNumber&&<Text style={s.hint}>{p.receiptNumber}</Text>}{manager&&p.status==='PENDING_VERIFICATION'&&button('Verify UPI '+p.reference,()=>Alert.alert('Verify payment','Confirm you have checked this transaction in the store bank account.',[{text:'Cancel',style:'cancel'},{text:'Verify',onPress:()=>action('/payments/'+p.id+'/verify',{decision:'VERIFY',version:p.version})}]),true)}</View>)}</View>)}</>}
 {tab==='Stock'&&<>{stockProduct&&<View style={s.card}><Text style={s.cardTitle}>Receive · {stockProduct.name}</Text>{field('Quantity',quantity,setQuantity,true)}{field('Reason / reference',reason,setReason)}{button('Receive stock',()=>action('/stock/receive',{productId:stockProduct.id,quantity:Number(quantity),reason},()=>{setStockProduct(null);setQuantity('');setReason('');}))}{button('Cancel',()=>setStockProduct(null),true)}</View>}{rows.map(p=><View key={p.id} style={s.card}><Text style={s.cardTitle}>{p.name}</Text><Text style={s.subtitle}>{p.sku}</Text><Text style={s.metricValue}>{p.onHand} units</Text><Text style={[s.hint,p.onHand<=p.minimumStock&&{color:'#b57836'}]}>{p.onHand<=p.minimumStock?'Low stock · ':''}Minimum {p.minimumStock}</Text>{inventory&&button('Receive stock',()=>setStockProduct(p),true)}</View>)}</>}
 {tab==='More'&&<><View style={s.card}><Text style={s.cardTitle}>{session.user.name}</Text><Text style={s.subtitle}>{session.user.role}</Text>{button('Sign out',()=>execute(async()=>{await api('/auth/logout',{});await clear();}))}</View>{manager&&<><Text style={s.section}>Event delivery</Text>{rows.map(n=><View key={n.id} style={s.card}><Text style={s.cardTitle}>{n.type}</Text><Text style={s.hint}>{n.status} · {new Date(n.createdAt).toLocaleString()}</Text></View>)}</>}<Text style={s.hint}>Customer OTP, packages, attendance, and payroll are planned for later phases.</Text></>}
 {!busy&&!rows.length&&['Appointments','Billing','Stock'].includes(tab)&&<Text style={s.empty}>No records yet. Your studio activity will appear here.</Text>}
 </ScrollView><View style={s.tabs}>{tabs.map(t=><Pressable accessibilityRole="tab" key={t} disabled={busy} onPress={()=>setTab(t)} style={s.tab}><Text style={[s.tabText,tab===t&&s.activeTab]}>{t}</Text>{tab===t&&<View style={s.tabDot}/>}</Pressable>)}</View></>}</SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f6f7f2'},login:{padding:32,paddingTop:95},logo:{fontSize:25,fontWeight:'800',letterSpacing:2,color:'#174f43'},eyebrow:{fontSize:8,letterSpacing:2,color:'#8b9e80',marginTop:7},title:{fontSize:27,fontWeight:'600',color:'#25422f',marginTop:24,marginBottom:10},subtitle:{fontSize:12,lineHeight:20,color:'#8a9b7d',marginBottom:14},field:{marginVertical:10},label:{fontSize:11,color:'#7c9070',marginBottom:8},input:{backgroundColor:'#fff',borderColor:'#dfe7d7',borderWidth:1,borderRadius:7,padding:13,color:'#25422f'},button:{backgroundColor:'#174f43',padding:14,borderRadius:7,alignItems:'center',marginVertical:6},buttonText:{color:'#fff',fontSize:12,fontWeight:'600'},secondary:{backgroundColor:'#edf2e7'},secondaryText:{color:'#597849'},hint:{fontSize:10,lineHeight:18,color:'#9aa58d',marginVertical:10},error:{backgroundColor:'#fbeae5',padding:14,borderRadius:6,color:'#a05641',marginVertical:12,fontSize:12},header:{padding:22,paddingTop:38,borderBottomWidth:1,borderColor:'#e6ecdf',flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#fff'},role:{fontSize:8,color:'#8a9e79',letterSpacing:1},content:{padding:22,paddingBottom:45},chip:{padding:10,borderWidth:1,borderColor:'#dfe7d7',borderRadius:6,marginRight:7},chipSelected:{backgroundColor:'#174f43',borderColor:'#174f43'},chipText:{fontSize:11,color:'#788b6d'},chipSelectedText:{fontSize:11,color:'#fff'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:18},metric:{backgroundColor:'#fff',padding:18,borderRadius:9,width:'47%',borderWidth:1,borderColor:'#e6ecdf'},metricValue:{fontSize:23,fontWeight:'600',color:'#2e4d24',marginVertical:5},section:{fontSize:16,fontWeight:'600',color:'#39592e',marginTop:28,marginBottom:12},card:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e5ebde',borderRadius:9,padding:18,marginVertical:8},cardTitle:{fontSize:14,fontWeight:'600',color:'#3b5932',marginBottom:7},status:{fontSize:10,color:'#73965f',marginBottom:10},empty:{textAlign:'center',padding:35,fontSize:12,color:'#9eab94'},tabs:{flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderColor:'#e6ecdf',paddingVertical:16},tab:{flex:1,alignItems:'center'},tabText:{fontSize:10,color:'#a0ac95'},activeTab:{color:'#174f43',fontWeight:'700'},tabDot:{width:4,height:4,borderRadius:2,backgroundColor:'#174f43',marginTop:6}});
